### ISSUE TITLE
Error while running features2cards

### ISSUE THREAD

**Issue by RoRoche** [brynary/features2cards#3]
Here is my system requirements:

- macOS Sierra, Version 10.12.3
- ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
- export PATH=/Users/Romain/.rbenv/versions/2.4.0/bin:$PATH

When running the following command `features2cards sum.feature`, I get the following stacktrace:

```
/Users/Romain/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/features2cards-0.4.0/lib/features2cards/platform.rb:8:in `<module:Features2Cards>': uninitialized constant Features2Cards::Config (NameError)
Did you mean?  RbConfig
	from /Users/Romain/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/features2cards-0.4.0/lib/features2cards/platform.rb:5:in `<top (required)>'
	from /Users/Romain/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/Romain/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/Romain/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/features2cards-0.4.0/lib/features2cards.rb:1:in `<top (required)>'
	from /Users/Romain/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/Romain/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/Romain/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/features2cards-0.4.0/bin/features2cards:3:in `<top (required)>'
	from /Users/Romain/.rbenv/versions/2.4.0/bin/features2cards:22:in `load'
	from /Users/Romain/.rbenv/versions/2.4.0/bin/features2cards:22:in `<main>'
```

How to get rid of this issue?

**Comment by Qqwy** [comment]
Exactly the same error, happening on Linux Mint 16, and Ruby 2.4.

**Comment by sebastianhaas** [comment]
Same here.
